name: go_rider
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.1.3
  logger: ^1.1.0
  equatable: ^2.0.5
  intl: ^0.17.0
  dio: ^5.3.1
  go_router: ^13.0.1
  provider: ^6.0.5
  google_maps_flutter: 2.2.6
  tutorial_coach_mark: ^1.2.11
  flutter_screenutil: ^5.3.1
  flutter_svg: ^2.0.7
  location: ^5.0.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  flutter_native_image: ^0.0.6+1
  
  shared_preferences: ^2.0.18
  flutter_rating_bar: ^4.0.1
  visibility_detector: ^0.4.0+2
  dash_chat_2: 
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_messaging: 
  flutter_local_notifications: ^16.3.2
  
  firebase_storage: ^11.6.0
  fluttertoast: ^8.2.4
  flutter_easyloading: ^3.0.5
  email_validator: 
  flutter_dotenv: ^5.1.0
  uuid: 
  flutter_timezone: ^1.0.7
  flutter_app_badger: ^1.5.0
   

dependency_overrides:
  flutter_polyline_points: 
  flutter_google_places_hoc081098: 
 
  

  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svgs/ 
    - assets/images/gorider.jpg
    - .env

